{
 "title": "Rancher Exporter Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "query0",
    "query": {
     "query": "rancherversion(rancher_major_version)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster Distribution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "K8s Distributions",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "3", "legendFormat": "RKE1" },
    { "expr": "7", "legendFormat": "RKE2" },
    { "expr": "4", "legendFormat": "K3s" },
    { "expr": "4", "legendFormat": "EKS" },
    { "expr": "2", "legendFormat": "AKS" },
    { "expr": "1", "legendFormat": "GKE" }
   ]
  },
  { "title": "Rancher Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Current Rancher Version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rancher_major_version" },
    { "expr": "rancher_minor_version" },
    { "expr": "rancher_patch_version" }
   ]
  },
  {
   "title": "Clusters Connected",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(cluster_connected)" }
   ]
  },
  {
   "title": "Clusters Disconnected",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(cluster_not_connected)" }
   ]
  },
  {
   "title": "Latest Rancher Version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 13, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "2" },
    { "expr": "6" },
    { "expr": "8" }
   ]
  },
  { "title": "Global Values", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Managed Node Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rancher_managed_nodes" }
   ]
  }
 ]
}